/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeMinimumMerchantSurfaceRouteImport } from './routes/prototype.minimum-merchant-surface'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMinimumMerchantSurfaceRoute =
  PrototypeMinimumMerchantSurfaceRouteImport.update({
    id: '/prototype/minimum-merchant-surface',
    path: '/prototype/minimum-merchant-surface',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototype/minimum-merchant-surface': typeof PrototypeMinimumMerchantSurfaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototype/minimum-merchant-surface': typeof PrototypeMinimumMerchantSurfaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototype/minimum-merchant-surface': typeof PrototypeMinimumMerchantSurfaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/prototype/minimum-merchant-surface'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/prototype/minimum-merchant-surface'
  id: '__root__' | '/' | '/prototype/minimum-merchant-surface'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototypeMinimumMerchantSurfaceRoute: typeof PrototypeMinimumMerchantSurfaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/minimum-merchant-surface': {
      id: '/prototype/minimum-merchant-surface'
      path: '/prototype/minimum-merchant-surface'
      fullPath: '/prototype/minimum-merchant-surface'
      preLoaderRoute: typeof PrototypeMinimumMerchantSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeMinimumMerchantSurfaceRoute: PrototypeMinimumMerchantSurfaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
