/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantSlugBookingRouteImport } from './routes/$merchantSlug.booking'
import { Route as MerchantSlugBookingSessionSessionIdRouteImport } from './routes/$merchantSlug.booking_.session.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSlugBookingRoute = MerchantSlugBookingRouteImport.update({
  id: '/$merchantSlug/booking',
  path: '/$merchantSlug/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSlugBookingSessionSessionIdRoute =
  MerchantSlugBookingSessionSessionIdRouteImport.update({
    id: '/$merchantSlug/booking_/session/$sessionId',
    path: '/$merchantSlug/booking/session/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$merchantSlug/booking': typeof MerchantSlugBookingRoute
  '/$merchantSlug/booking/session/$sessionId': typeof MerchantSlugBookingSessionSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$merchantSlug/booking': typeof MerchantSlugBookingRoute
  '/$merchantSlug/booking/session/$sessionId': typeof MerchantSlugBookingSessionSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$merchantSlug/booking': typeof MerchantSlugBookingRoute
  '/$merchantSlug/booking_/session/$sessionId': typeof MerchantSlugBookingSessionSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$merchantSlug/booking'
    | '/$merchantSlug/booking/session/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$merchantSlug/booking'
    | '/$merchantSlug/booking/session/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/$merchantSlug/booking'
    | '/$merchantSlug/booking_/session/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantSlugBookingRoute: typeof MerchantSlugBookingRoute
  MerchantSlugBookingSessionSessionIdRoute: typeof MerchantSlugBookingSessionSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$merchantSlug/booking': {
      id: '/$merchantSlug/booking'
      path: '/$merchantSlug/booking'
      fullPath: '/$merchantSlug/booking'
      preLoaderRoute: typeof MerchantSlugBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$merchantSlug/booking_/session/$sessionId': {
      id: '/$merchantSlug/booking_/session/$sessionId'
      path: '/$merchantSlug/booking/session/$sessionId'
      fullPath: '/$merchantSlug/booking/session/$sessionId'
      preLoaderRoute: typeof MerchantSlugBookingSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantSlugBookingRoute: MerchantSlugBookingRoute,
  MerchantSlugBookingSessionSessionIdRoute:
    MerchantSlugBookingSessionSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
