/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeRouteImport } from './routes/_knowledge'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TwoFactorRouteImport } from './routes/two-factor'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as KnowledgeChangelogRouteImport } from './routes/_knowledge.changelog'
import { Route as KnowledgeFaqRouteImport } from './routes/_knowledge.faq'
import { Route as AccountNotificationsRouteImport } from './routes/account_.notifications'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known.oauth-authorization-server'
import { Route as KnowledgeChangelogRouteImport } from './routes/_knowledge.changelog'
import { Route as KnowledgeFaqRouteImport } from './routes/_knowledge.faq'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as DotwellKnownOauthAuthorizationServerSplatRouteImport } from './routes/[.]well-known.oauth-authorization-server.$'
import { Route as KnowledgeBlogIndexRouteImport } from './routes/_knowledge.blog.index'
import { Route as KnowledgeBlogSlugRouteImport } from './routes/_knowledge.blog.$slug'
import { Route as KnowledgeDocsIndexRouteImport } from './routes/_knowledge.docs.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as WorkspacesWorkspaceSlugIndexRouteImport } from './routes/workspaces.$workspaceSlug.index'
import { Route as WorkspacesWorkspaceSlugApiTokensRouteImport } from './routes/workspaces.$workspaceSlug.api-tokens'
import { Route as WorkspacesWorkspaceSlugAssistantRouteImport } from './routes/workspaces.$workspaceSlug.assistant'
import { Route as WorkspacesWorkspaceSlugAuditRouteImport } from './routes/workspaces.$workspaceSlug.audit'
import { Route as WorkspacesWorkspaceSlugBillingRouteImport } from './routes/workspaces.$workspaceSlug.billing'
import { Route as WorkspacesWorkspaceSlugMembersRouteImport } from './routes/workspaces.$workspaceSlug.members'
import { Route as WorkspacesWorkspaceSlugSettingsRouteImport } from './routes/workspaces.$workspaceSlug.settings'
import { Route as WorkspacesWorkspaceSlugWebhooksRouteImport } from './routes/workspaces.$workspaceSlug.webhooks'
import { Route as KnowledgeDocsCategorySlugRouteImport } from './routes/_knowledge.docs.$category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/_knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TwoFactorRoute = TwoFactorRouteImport.update({
  id: '/two-factor',
  path: '/two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeChangelogRoute = KnowledgeChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeFaqRoute = KnowledgeFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => KnowledgeRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account_/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const DotwellKnownOauthAuthorizationServerSplatRoute =
  DotwellKnownOauthAuthorizationServerSplatRouteImport.update({
    id: '/$',
    path: '/$',
    getParentRoute: () => DotwellKnownOauthAuthorizationServerRoute,
  } as any)
const KnowledgeBlogIndexRoute = KnowledgeBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeBlogSlugRoute = KnowledgeBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeDocsIndexRoute = KnowledgeDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesWorkspaceSlugIndexRoute =
  WorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/$workspaceSlug/',
    path: '/$workspaceSlug/',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugApiTokensRoute =
  WorkspacesWorkspaceSlugApiTokensRouteImport.update({
    id: '/$workspaceSlug/api-tokens',
    path: '/$workspaceSlug/api-tokens',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugAssistantRoute =
  WorkspacesWorkspaceSlugAssistantRouteImport.update({
    id: '/$workspaceSlug/assistant',
    path: '/$workspaceSlug/assistant',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugAuditRoute =
  WorkspacesWorkspaceSlugAuditRouteImport.update({
    id: '/$workspaceSlug/audit',
    path: '/$workspaceSlug/audit',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugBillingRoute =
  WorkspacesWorkspaceSlugBillingRouteImport.update({
    id: '/$workspaceSlug/billing',
    path: '/$workspaceSlug/billing',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugMembersRoute =
  WorkspacesWorkspaceSlugMembersRouteImport.update({
    id: '/$workspaceSlug/members',
    path: '/$workspaceSlug/members',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugSettingsRoute =
  WorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/$workspaceSlug/settings',
    path: '/$workspaceSlug/settings',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugWebhooksRoute =
  WorkspacesWorkspaceSlugWebhooksRouteImport.update({
    id: '/$workspaceSlug/webhooks',
    path: '/$workspaceSlug/webhooks',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const KnowledgeDocsCategorySlugRoute =
  KnowledgeDocsCategorySlugRouteImport.update({
    id: '/docs/$category/$slug',
    path: '/docs/$category/$slug',
    getParentRoute: () => KnowledgeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/changelog': typeof KnowledgeChangelogRoute
  '/faq': typeof KnowledgeFaqRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/changelog': typeof KnowledgeChangelogRoute
  '/faq': typeof KnowledgeFaqRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/help/': typeof HelpIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/blog/$slug': typeof KnowledgeBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/assistant': typeof WorkspacesWorkspaceSlugAssistantRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/billing': typeof WorkspacesWorkspaceSlugBillingRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/blog/': typeof KnowledgeBlogIndexRoute
  '/docs/': typeof KnowledgeDocsIndexRoute
  '/workspaces/$workspaceSlug/': typeof WorkspacesWorkspaceSlugIndexRoute
  '/docs/$category/$slug': typeof KnowledgeDocsCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/changelog': typeof KnowledgeChangelogRoute
  '/faq': typeof KnowledgeFaqRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/changelog': typeof KnowledgeChangelogRoute
  '/faq': typeof KnowledgeFaqRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/help': typeof HelpIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/blog/$slug': typeof KnowledgeBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/assistant': typeof WorkspacesWorkspaceSlugAssistantRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/billing': typeof WorkspacesWorkspaceSlugBillingRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/blog': typeof KnowledgeBlogIndexRoute
  '/docs': typeof KnowledgeDocsIndexRoute
  '/workspaces/$workspaceSlug': typeof WorkspacesWorkspaceSlugIndexRoute
  '/docs/$category/$slug': typeof KnowledgeDocsCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_knowledge': typeof KnowledgeRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/demo': typeof DemoRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/two-factor': typeof TwoFactorRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/_knowledge/changelog': typeof KnowledgeChangelogRoute
  '/_knowledge/faq': typeof KnowledgeFaqRoute
  '/account_/notifications': typeof AccountNotificationsRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  '/_knowledge/changelog': typeof KnowledgeChangelogRoute
  '/_knowledge/faq': typeof KnowledgeFaqRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/help/': typeof HelpIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/.well-known/oauth-authorization-server/$': typeof DotwellKnownOauthAuthorizationServerSplatRoute
  '/_knowledge/blog/$slug': typeof KnowledgeBlogSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/assistant': typeof WorkspacesWorkspaceSlugAssistantRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/billing': typeof WorkspacesWorkspaceSlugBillingRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/_knowledge/blog/': typeof KnowledgeBlogIndexRoute
  '/_knowledge/docs/': typeof KnowledgeDocsIndexRoute
  '/workspaces/$workspaceSlug/': typeof WorkspacesWorkspaceSlugIndexRoute
  '/_knowledge/docs/$category/$slug': typeof KnowledgeDocsCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/two-factor'
    | '/verify-email'
    | '/workspaces'
    | '/changelog'
    | '/faq'
    | '/account/notifications'
    | '/.well-known/oauth-authorization-server'
    | '/changelog'
    | '/faq'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/help/'
    | '/workspaces/'
    | '/.well-known/oauth-authorization-server/$'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/assistant'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/billing'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/blog/'
    | '/docs/'
    | '/workspaces/$workspaceSlug/'
    | '/docs/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/two-factor'
    | '/verify-email'
    | '/changelog'
    | '/faq'
    | '/account/notifications'
    | '/.well-known/oauth-authorization-server'
    | '/changelog'
    | '/faq'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/help'
    | '/workspaces'
    | '/.well-known/oauth-authorization-server/$'
    | '/blog/$slug'
    | '/api/auth/$'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/assistant'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/billing'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/blog'
    | '/docs'
    | '/workspaces/$workspaceSlug'
    | '/docs/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/_knowledge'
    | '/account'
    | '/admin'
    | '/demo'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/two-factor'
    | '/verify-email'
    | '/workspaces'
    | '/_knowledge/changelog'
    | '/_knowledge/faq'
    | '/account_/notifications'
    | '/.well-known/oauth-authorization-server'
    | '/_knowledge/changelog'
    | '/_knowledge/faq'
    | '/invitations/accept'
    | '/oauth/consent'
    | '/help/'
    | '/workspaces/'
    | '/.well-known/oauth-authorization-server/$'
    | '/_knowledge/blog/$slug'
    | '/api/auth/$'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/assistant'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/billing'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/_knowledge/blog/'
    | '/_knowledge/docs/'
    | '/workspaces/$workspaceSlug/'
    | '/_knowledge/docs/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DemoRoute: typeof DemoRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  TwoFactorRoute: typeof TwoFactorRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRouteWithChildren
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  OauthConsentRoute: typeof OauthConsentRoute
  HelpIndexRoute: typeof HelpIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_knowledge': {
      id: '/_knowledge'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/two-factor': {
      id: '/two-factor'
      path: '/two-factor'
      fullPath: '/two-factor'
      preLoaderRoute: typeof TwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_knowledge/changelog': {
      id: '/_knowledge/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof KnowledgeChangelogRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_knowledge/faq': {
      id: '/_knowledge/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof KnowledgeFaqRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/account_/notifications': {
      id: '/account_/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/.well-known/oauth-authorization-server/$': {
      id: '/.well-known/oauth-authorization-server/$'
      path: '/$'
      fullPath: '/.well-known/oauth-authorization-server/$'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerSplatRouteImport
      parentRoute: typeof DotwellKnownOauthAuthorizationServerRoute
    }
    '/_knowledge/blog/': {
      id: '/_knowledge/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof KnowledgeBlogIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_knowledge/blog/$slug': {
      id: '/_knowledge/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof KnowledgeBlogSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/_knowledge/docs/': {
      id: '/_knowledge/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof KnowledgeDocsIndexRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/$workspaceSlug/': {
      id: '/workspaces/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/api-tokens': {
      id: '/workspaces/$workspaceSlug/api-tokens'
      path: '/$workspaceSlug/api-tokens'
      fullPath: '/workspaces/$workspaceSlug/api-tokens'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugApiTokensRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/assistant': {
      id: '/workspaces/$workspaceSlug/assistant'
      path: '/$workspaceSlug/assistant'
      fullPath: '/workspaces/$workspaceSlug/assistant'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugAssistantRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/audit': {
      id: '/workspaces/$workspaceSlug/audit'
      path: '/$workspaceSlug/audit'
      fullPath: '/workspaces/$workspaceSlug/audit'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugAuditRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/billing': {
      id: '/workspaces/$workspaceSlug/billing'
      path: '/$workspaceSlug/billing'
      fullPath: '/workspaces/$workspaceSlug/billing'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugBillingRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/members': {
      id: '/workspaces/$workspaceSlug/members'
      path: '/$workspaceSlug/members'
      fullPath: '/workspaces/$workspaceSlug/members'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugMembersRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/settings': {
      id: '/workspaces/$workspaceSlug/settings'
      path: '/$workspaceSlug/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/webhooks': {
      id: '/workspaces/$workspaceSlug/webhooks'
      path: '/$workspaceSlug/webhooks'
      fullPath: '/workspaces/$workspaceSlug/webhooks'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugWebhooksRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/_knowledge/docs/$category/$slug': {
      id: '/_knowledge/docs/$category/$slug'
      path: '/docs/$category/$slug'
      fullPath: '/docs/$category/$slug'
      preLoaderRoute: typeof KnowledgeDocsCategorySlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeChangelogRoute: typeof KnowledgeChangelogRoute
  KnowledgeFaqRoute: typeof KnowledgeFaqRoute
  KnowledgeBlogSlugRoute: typeof KnowledgeBlogSlugRoute
  KnowledgeBlogIndexRoute: typeof KnowledgeBlogIndexRoute
  KnowledgeDocsIndexRoute: typeof KnowledgeDocsIndexRoute
  KnowledgeDocsCategorySlugRoute: typeof KnowledgeDocsCategorySlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeChangelogRoute: KnowledgeChangelogRoute,
  KnowledgeFaqRoute: KnowledgeFaqRoute,
  KnowledgeBlogSlugRoute: KnowledgeBlogSlugRoute,
  KnowledgeBlogIndexRoute: KnowledgeBlogIndexRoute,
  KnowledgeDocsIndexRoute: KnowledgeDocsIndexRoute,
  KnowledgeDocsCategorySlugRoute: KnowledgeDocsCategorySlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface WorkspacesRouteChildren {
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  WorkspacesWorkspaceSlugApiTokensRoute: typeof WorkspacesWorkspaceSlugApiTokensRoute
  WorkspacesWorkspaceSlugAssistantRoute: typeof WorkspacesWorkspaceSlugAssistantRoute
  WorkspacesWorkspaceSlugAuditRoute: typeof WorkspacesWorkspaceSlugAuditRoute
  WorkspacesWorkspaceSlugBillingRoute: typeof WorkspacesWorkspaceSlugBillingRoute
  WorkspacesWorkspaceSlugMembersRoute: typeof WorkspacesWorkspaceSlugMembersRoute
  WorkspacesWorkspaceSlugSettingsRoute: typeof WorkspacesWorkspaceSlugSettingsRoute
  WorkspacesWorkspaceSlugWebhooksRoute: typeof WorkspacesWorkspaceSlugWebhooksRoute
  WorkspacesWorkspaceSlugIndexRoute: typeof WorkspacesWorkspaceSlugIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  WorkspacesWorkspaceSlugApiTokensRoute: WorkspacesWorkspaceSlugApiTokensRoute,
  WorkspacesWorkspaceSlugAssistantRoute: WorkspacesWorkspaceSlugAssistantRoute,
  WorkspacesWorkspaceSlugAuditRoute: WorkspacesWorkspaceSlugAuditRoute,
  WorkspacesWorkspaceSlugBillingRoute: WorkspacesWorkspaceSlugBillingRoute,
  WorkspacesWorkspaceSlugMembersRoute: WorkspacesWorkspaceSlugMembersRoute,
  WorkspacesWorkspaceSlugSettingsRoute: WorkspacesWorkspaceSlugSettingsRoute,
  WorkspacesWorkspaceSlugWebhooksRoute: WorkspacesWorkspaceSlugWebhooksRoute,
  WorkspacesWorkspaceSlugIndexRoute: WorkspacesWorkspaceSlugIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

interface DotwellKnownOauthAuthorizationServerRouteChildren {
  DotwellKnownOauthAuthorizationServerSplatRoute: typeof DotwellKnownOauthAuthorizationServerSplatRoute
}

const DotwellKnownOauthAuthorizationServerRouteChildren: DotwellKnownOauthAuthorizationServerRouteChildren =
  {
    DotwellKnownOauthAuthorizationServerSplatRoute:
      DotwellKnownOauthAuthorizationServerSplatRoute,
  }

const DotwellKnownOauthAuthorizationServerRouteWithChildren =
  DotwellKnownOauthAuthorizationServerRoute._addFileChildren(
    DotwellKnownOauthAuthorizationServerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DemoRoute: DemoRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  TwoFactorRoute: TwoFactorRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  AccountNotificationsRoute: AccountNotificationsRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRouteWithChildren,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  OauthConsentRoute: OauthConsentRoute,
  HelpIndexRoute: HelpIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
