/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as HelpIndexRouteImport } from './routes/help.index'
import { Route as InvitationsAcceptRouteImport } from './routes/invitations.accept'
import { Route as WorkspacesIndexRouteImport } from './routes/workspaces.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as DocsCategorySlugRouteImport } from './routes/docs.$category.$slug'
import { Route as WorkspacesWorkspaceSlugIndexRouteImport } from './routes/workspaces.$workspaceSlug.index'
import { Route as WorkspacesWorkspaceSlugApiTokensRouteImport } from './routes/workspaces.$workspaceSlug.api-tokens'
import { Route as WorkspacesWorkspaceSlugAuditRouteImport } from './routes/workspaces.$workspaceSlug.audit'
import { Route as WorkspacesWorkspaceSlugMembersRouteImport } from './routes/workspaces.$workspaceSlug.members'
import { Route as WorkspacesWorkspaceSlugSettingsRouteImport } from './routes/workspaces.$workspaceSlug.settings'
import { Route as WorkspacesWorkspaceSlugWebhooksRouteImport } from './routes/workspaces.$workspaceSlug.webhooks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsAcceptRoute = InvitationsAcceptRouteImport.update({
  id: '/invitations/accept',
  path: '/invitations/accept',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesIndexRoute = WorkspacesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspacesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCategorySlugRoute = DocsCategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const WorkspacesWorkspaceSlugIndexRoute =
  WorkspacesWorkspaceSlugIndexRouteImport.update({
    id: '/$workspaceSlug/',
    path: '/$workspaceSlug/',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugApiTokensRoute =
  WorkspacesWorkspaceSlugApiTokensRouteImport.update({
    id: '/$workspaceSlug/api-tokens',
    path: '/$workspaceSlug/api-tokens',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugAuditRoute =
  WorkspacesWorkspaceSlugAuditRouteImport.update({
    id: '/$workspaceSlug/audit',
    path: '/$workspaceSlug/audit',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugMembersRoute =
  WorkspacesWorkspaceSlugMembersRouteImport.update({
    id: '/$workspaceSlug/members',
    path: '/$workspaceSlug/members',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugSettingsRoute =
  WorkspacesWorkspaceSlugSettingsRouteImport.update({
    id: '/$workspaceSlug/settings',
    path: '/$workspaceSlug/settings',
    getParentRoute: () => WorkspacesRoute,
  } as any)
const WorkspacesWorkspaceSlugWebhooksRoute =
  WorkspacesWorkspaceSlugWebhooksRouteImport.update({
    id: '/$workspaceSlug/webhooks',
    path: '/$workspaceSlug/webhooks',
    getParentRoute: () => WorkspacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/workspaces/$workspaceSlug/': typeof WorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/blog': typeof BlogIndexRoute
  '/docs': typeof DocsIndexRoute
  '/help': typeof HelpIndexRoute
  '/workspaces': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/workspaces/$workspaceSlug': typeof WorkspacesWorkspaceSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/changelog': typeof ChangelogRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/workspaces': typeof WorkspacesRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/invitations/accept': typeof InvitationsAcceptRoute
  '/blog/': typeof BlogIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/help/': typeof HelpIndexRoute
  '/workspaces/': typeof WorkspacesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/docs/$category/$slug': typeof DocsCategorySlugRoute
  '/workspaces/$workspaceSlug/api-tokens': typeof WorkspacesWorkspaceSlugApiTokensRoute
  '/workspaces/$workspaceSlug/audit': typeof WorkspacesWorkspaceSlugAuditRoute
  '/workspaces/$workspaceSlug/members': typeof WorkspacesWorkspaceSlugMembersRoute
  '/workspaces/$workspaceSlug/settings': typeof WorkspacesWorkspaceSlugSettingsRoute
  '/workspaces/$workspaceSlug/webhooks': typeof WorkspacesWorkspaceSlugWebhooksRoute
  '/workspaces/$workspaceSlug/': typeof WorkspacesWorkspaceSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/changelog'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/verify-email'
    | '/workspaces'
    | '/blog/$slug'
    | '/invitations/accept'
    | '/blog/'
    | '/docs/'
    | '/help/'
    | '/workspaces/'
    | '/api/auth/$'
    | '/docs/$category/$slug'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/workspaces/$workspaceSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/changelog'
    | '/faq'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/verify-email'
    | '/blog/$slug'
    | '/invitations/accept'
    | '/blog'
    | '/docs'
    | '/help'
    | '/workspaces'
    | '/api/auth/$'
    | '/docs/$category/$slug'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/workspaces/$workspaceSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/changelog'
    | '/docs'
    | '/faq'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
    | '/verify-email'
    | '/workspaces'
    | '/blog/$slug'
    | '/invitations/accept'
    | '/blog/'
    | '/docs/'
    | '/help/'
    | '/workspaces/'
    | '/api/auth/$'
    | '/docs/$category/$slug'
    | '/workspaces/$workspaceSlug/api-tokens'
    | '/workspaces/$workspaceSlug/audit'
    | '/workspaces/$workspaceSlug/members'
    | '/workspaces/$workspaceSlug/settings'
    | '/workspaces/$workspaceSlug/webhooks'
    | '/workspaces/$workspaceSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChangelogRoute: typeof ChangelogRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WorkspacesRoute: typeof WorkspacesRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  InvitationsAcceptRoute: typeof InvitationsAcceptRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/accept': {
      id: '/invitations/accept'
      path: '/invitations/accept'
      fullPath: '/invitations/accept'
      preLoaderRoute: typeof InvitationsAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/': {
      id: '/workspaces/'
      path: '/'
      fullPath: '/workspaces/'
      preLoaderRoute: typeof WorkspacesIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$category/$slug': {
      id: '/docs/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/docs/$category/$slug'
      preLoaderRoute: typeof DocsCategorySlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/workspaces/$workspaceSlug/': {
      id: '/workspaces/$workspaceSlug/'
      path: '/$workspaceSlug'
      fullPath: '/workspaces/$workspaceSlug/'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugIndexRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/api-tokens': {
      id: '/workspaces/$workspaceSlug/api-tokens'
      path: '/$workspaceSlug/api-tokens'
      fullPath: '/workspaces/$workspaceSlug/api-tokens'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugApiTokensRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/audit': {
      id: '/workspaces/$workspaceSlug/audit'
      path: '/$workspaceSlug/audit'
      fullPath: '/workspaces/$workspaceSlug/audit'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugAuditRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/members': {
      id: '/workspaces/$workspaceSlug/members'
      path: '/$workspaceSlug/members'
      fullPath: '/workspaces/$workspaceSlug/members'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugMembersRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/settings': {
      id: '/workspaces/$workspaceSlug/settings'
      path: '/$workspaceSlug/settings'
      fullPath: '/workspaces/$workspaceSlug/settings'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugSettingsRouteImport
      parentRoute: typeof WorkspacesRoute
    }
    '/workspaces/$workspaceSlug/webhooks': {
      id: '/workspaces/$workspaceSlug/webhooks'
      path: '/$workspaceSlug/webhooks'
      fullPath: '/workspaces/$workspaceSlug/webhooks'
      preLoaderRoute: typeof WorkspacesWorkspaceSlugWebhooksRouteImport
      parentRoute: typeof WorkspacesRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCategorySlugRoute: typeof DocsCategorySlugRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsCategorySlugRoute: DocsCategorySlugRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface WorkspacesRouteChildren {
  WorkspacesIndexRoute: typeof WorkspacesIndexRoute
  WorkspacesWorkspaceSlugApiTokensRoute: typeof WorkspacesWorkspaceSlugApiTokensRoute
  WorkspacesWorkspaceSlugAuditRoute: typeof WorkspacesWorkspaceSlugAuditRoute
  WorkspacesWorkspaceSlugMembersRoute: typeof WorkspacesWorkspaceSlugMembersRoute
  WorkspacesWorkspaceSlugSettingsRoute: typeof WorkspacesWorkspaceSlugSettingsRoute
  WorkspacesWorkspaceSlugWebhooksRoute: typeof WorkspacesWorkspaceSlugWebhooksRoute
  WorkspacesWorkspaceSlugIndexRoute: typeof WorkspacesWorkspaceSlugIndexRoute
}

const WorkspacesRouteChildren: WorkspacesRouteChildren = {
  WorkspacesIndexRoute: WorkspacesIndexRoute,
  WorkspacesWorkspaceSlugApiTokensRoute: WorkspacesWorkspaceSlugApiTokensRoute,
  WorkspacesWorkspaceSlugAuditRoute: WorkspacesWorkspaceSlugAuditRoute,
  WorkspacesWorkspaceSlugMembersRoute: WorkspacesWorkspaceSlugMembersRoute,
  WorkspacesWorkspaceSlugSettingsRoute: WorkspacesWorkspaceSlugSettingsRoute,
  WorkspacesWorkspaceSlugWebhooksRoute: WorkspacesWorkspaceSlugWebhooksRoute,
  WorkspacesWorkspaceSlugIndexRoute: WorkspacesWorkspaceSlugIndexRoute,
}

const WorkspacesRouteWithChildren = WorkspacesRoute._addFileChildren(
  WorkspacesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChangelogRoute: ChangelogRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WorkspacesRoute: WorkspacesRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  InvitationsAcceptRoute: InvitationsAcceptRoute,
  BlogIndexRoute: BlogIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
