/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyTotpRouteImport } from './routes/verify-totp'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants.$merchantId'
import { Route as EnrollSecurityRouteImport } from './routes/enroll.security'
import { Route as AuditEventIdRouteImport } from './routes/audit.$eventId'
import { Route as OperatorsInvitationsNewRouteImport } from './routes/operators.invitations.new'
import { Route as MerchantsMerchantIdMembersMemberIdRouteImport } from './routes/merchants.$merchantId.members.$memberId'

const VerifyTotpRoute = VerifyTotpRouteImport.update({
  id: '/verify-totp',
  path: '/verify-totp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/merchants/$merchantId',
  path: '/merchants/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollSecurityRoute = EnrollSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => EnrollRoute,
} as any)
const AuditEventIdRoute = AuditEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => AuditRoute,
} as any)
const OperatorsInvitationsNewRoute = OperatorsInvitationsNewRouteImport.update({
  id: '/invitations/new',
  path: '/invitations/new',
  getParentRoute: () => OperatorsRoute,
} as any)
const MerchantsMerchantIdMembersMemberIdRoute =
  MerchantsMerchantIdMembersMemberIdRouteImport.update({
    id: '/members/$memberId',
    path: '/members/$memberId',
    getParentRoute: () => MerchantsMerchantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/enroll': typeof EnrollRouteWithChildren
  '/operators': typeof OperatorsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/audit/$eventId': typeof AuditEventIdRoute
  '/enroll/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRouteWithChildren
  '/operators/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/enroll': typeof EnrollRouteWithChildren
  '/operators': typeof OperatorsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/audit/$eventId': typeof AuditEventIdRoute
  '/enroll/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRouteWithChildren
  '/operators/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/enroll': typeof EnrollRouteWithChildren
  '/operators': typeof OperatorsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/audit/$eventId': typeof AuditEventIdRoute
  '/enroll/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRouteWithChildren
  '/operators/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/sign-in'
    | '/verify-totp'
    | '/audit/$eventId'
    | '/enroll/security'
    | '/merchants/$merchantId'
    | '/operators/invitations/new'
    | '/merchants/$merchantId/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/sign-in'
    | '/verify-totp'
    | '/audit/$eventId'
    | '/enroll/security'
    | '/merchants/$merchantId'
    | '/operators/invitations/new'
    | '/merchants/$merchantId/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/sign-in'
    | '/verify-totp'
    | '/audit/$eventId'
    | '/enroll/security'
    | '/merchants/$merchantId'
    | '/operators/invitations/new'
    | '/merchants/$merchantId/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRouteWithChildren
  EnrollRoute: typeof EnrollRouteWithChildren
  OperatorsRoute: typeof OperatorsRouteWithChildren
  SignInRoute: typeof SignInRoute
  VerifyTotpRoute: typeof VerifyTotpRoute
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-totp': {
      id: '/verify-totp'
      path: '/verify-totp'
      fullPath: '/verify-totp'
      preLoaderRoute: typeof VerifyTotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll/security': {
      id: '/enroll/security'
      path: '/security'
      fullPath: '/enroll/security'
      preLoaderRoute: typeof EnrollSecurityRouteImport
      parentRoute: typeof EnrollRoute
    }
    '/audit/$eventId': {
      id: '/audit/$eventId'
      path: '/$eventId'
      fullPath: '/audit/$eventId'
      preLoaderRoute: typeof AuditEventIdRouteImport
      parentRoute: typeof AuditRoute
    }
    '/operators/invitations/new': {
      id: '/operators/invitations/new'
      path: '/invitations/new'
      fullPath: '/operators/invitations/new'
      preLoaderRoute: typeof OperatorsInvitationsNewRouteImport
      parentRoute: typeof OperatorsRoute
    }
    '/merchants/$merchantId/members/$memberId': {
      id: '/merchants/$merchantId/members/$memberId'
      path: '/members/$memberId'
      fullPath: '/merchants/$merchantId/members/$memberId'
      preLoaderRoute: typeof MerchantsMerchantIdMembersMemberIdRouteImport
      parentRoute: typeof MerchantsMerchantIdRoute
    }
  }
}

interface AuditRouteChildren {
  AuditEventIdRoute: typeof AuditEventIdRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditEventIdRoute: AuditEventIdRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

interface EnrollRouteChildren {
  EnrollSecurityRoute: typeof EnrollSecurityRoute
}

const EnrollRouteChildren: EnrollRouteChildren = {
  EnrollSecurityRoute: EnrollSecurityRoute,
}

const EnrollRouteWithChildren =
  EnrollRoute._addFileChildren(EnrollRouteChildren)

interface OperatorsRouteChildren {
  OperatorsInvitationsNewRoute: typeof OperatorsInvitationsNewRoute
}

const OperatorsRouteChildren: OperatorsRouteChildren = {
  OperatorsInvitationsNewRoute: OperatorsInvitationsNewRoute,
}

const OperatorsRouteWithChildren = OperatorsRoute._addFileChildren(
  OperatorsRouteChildren,
)

interface MerchantsMerchantIdRouteChildren {
  MerchantsMerchantIdMembersMemberIdRoute: typeof MerchantsMerchantIdMembersMemberIdRoute
}

const MerchantsMerchantIdRouteChildren: MerchantsMerchantIdRouteChildren = {
  MerchantsMerchantIdMembersMemberIdRoute:
    MerchantsMerchantIdMembersMemberIdRoute,
}

const MerchantsMerchantIdRouteWithChildren =
  MerchantsMerchantIdRoute._addFileChildren(MerchantsMerchantIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRouteWithChildren,
  EnrollRoute: EnrollRouteWithChildren,
  OperatorsRoute: OperatorsRouteWithChildren,
  SignInRoute: SignInRoute,
  VerifyTotpRoute: VerifyTotpRoute,
  MerchantsMerchantIdRoute: MerchantsMerchantIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
