/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyTotpRouteImport } from './routes/verify-totp'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReadyRouteImport } from './routes/ready'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as EnrollRouteImport } from './routes/enroll'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantsMerchantIdRouteImport } from './routes/merchants.$merchantId'
import { Route as EnrollSecurityRouteImport } from './routes/enroll_.security'
import { Route as AuditEventIdRouteImport } from './routes/audit_.$eventId'
import { Route as _localOperatorInvitationEmailRouteImport } from './routes/[_][_]local.operator-invitation-email'
import { Route as OperatorsInvitationsNewRouteImport } from './routes/operators_.invitations.new'
import { Route as ApiOperationsSplatRouteImport } from './routes/api.operations.$'
import { Route as ApiMerchantsSplatRouteImport } from './routes/api.merchants.$'
import { Route as ApiMembersSearchRouteImport } from './routes/api.members.search'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as MerchantsMerchantIdMembersMemberIdRouteImport } from './routes/merchants.$merchantId_.members.$memberId'

const VerifyTotpRoute = VerifyTotpRouteImport.update({
  id: '/verify-totp',
  path: '/verify-totp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadyRoute = ReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollRoute = EnrollRouteImport.update({
  id: '/enroll',
  path: '/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsMerchantIdRoute = MerchantsMerchantIdRouteImport.update({
  id: '/merchants/$merchantId',
  path: '/merchants/$merchantId',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollSecurityRoute = EnrollSecurityRouteImport.update({
  id: '/enroll_/security',
  path: '/enroll/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditEventIdRoute = AuditEventIdRouteImport.update({
  id: '/audit_/$eventId',
  path: '/audit/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const _localOperatorInvitationEmailRoute =
  _localOperatorInvitationEmailRouteImport.update({
    id: '/__local/operator-invitation-email',
    path: '/__local/operator-invitation-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperatorsInvitationsNewRoute = OperatorsInvitationsNewRouteImport.update({
  id: '/operators_/invitations/new',
  path: '/operators/invitations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOperationsSplatRoute = ApiOperationsSplatRouteImport.update({
  id: '/api/operations/$',
  path: '/api/operations/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMerchantsSplatRoute = ApiMerchantsSplatRouteImport.update({
  id: '/api/merchants/$',
  path: '/api/merchants/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMembersSearchRoute = ApiMembersSearchRouteImport.update({
  id: '/api/members/search',
  path: '/api/members/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantsMerchantIdMembersMemberIdRoute =
  MerchantsMerchantIdMembersMemberIdRouteImport.update({
    id: '/merchants/$merchantId_/members/$memberId',
    path: '/merchants/$merchantId/members/$memberId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/enroll': typeof EnrollRoute
  '/operators': typeof OperatorsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/__local/operator-invitation-email': typeof _localOperatorInvitationEmailRoute
  '/audit/$eventId': typeof AuditEventIdRoute
  '/enroll/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/members/search': typeof ApiMembersSearchRoute
  '/api/merchants/$': typeof ApiMerchantsSplatRoute
  '/api/operations/$': typeof ApiOperationsSplatRoute
  '/operators/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/enroll': typeof EnrollRoute
  '/operators': typeof OperatorsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/__local/operator-invitation-email': typeof _localOperatorInvitationEmailRoute
  '/audit/$eventId': typeof AuditEventIdRoute
  '/enroll/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/members/search': typeof ApiMembersSearchRoute
  '/api/merchants/$': typeof ApiMerchantsSplatRoute
  '/api/operations/$': typeof ApiOperationsSplatRoute
  '/operators/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/enroll': typeof EnrollRoute
  '/operators': typeof OperatorsRoute
  '/ready': typeof ReadyRoute
  '/sign-in': typeof SignInRoute
  '/verify-totp': typeof VerifyTotpRoute
  '/__local/operator-invitation-email': typeof _localOperatorInvitationEmailRoute
  '/audit_/$eventId': typeof AuditEventIdRoute
  '/enroll_/security': typeof EnrollSecurityRoute
  '/merchants/$merchantId': typeof MerchantsMerchantIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/members/search': typeof ApiMembersSearchRoute
  '/api/merchants/$': typeof ApiMerchantsSplatRoute
  '/api/operations/$': typeof ApiOperationsSplatRoute
  '/operators_/invitations/new': typeof OperatorsInvitationsNewRoute
  '/merchants/$merchantId_/members/$memberId': typeof MerchantsMerchantIdMembersMemberIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/ready'
    | '/sign-in'
    | '/verify-totp'
    | '/__local/operator-invitation-email'
    | '/audit/$eventId'
    | '/enroll/security'
    | '/merchants/$merchantId'
    | '/api/auth/$'
    | '/api/members/search'
    | '/api/merchants/$'
    | '/api/operations/$'
    | '/operators/invitations/new'
    | '/merchants/$merchantId/members/$memberId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/ready'
    | '/sign-in'
    | '/verify-totp'
    | '/__local/operator-invitation-email'
    | '/audit/$eventId'
    | '/enroll/security'
    | '/merchants/$merchantId'
    | '/api/auth/$'
    | '/api/members/search'
    | '/api/merchants/$'
    | '/api/operations/$'
    | '/operators/invitations/new'
    | '/merchants/$merchantId/members/$memberId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/enroll'
    | '/operators'
    | '/ready'
    | '/sign-in'
    | '/verify-totp'
    | '/__local/operator-invitation-email'
    | '/audit_/$eventId'
    | '/enroll_/security'
    | '/merchants/$merchantId'
    | '/api/auth/$'
    | '/api/members/search'
    | '/api/merchants/$'
    | '/api/operations/$'
    | '/operators_/invitations/new'
    | '/merchants/$merchantId_/members/$memberId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  EnrollRoute: typeof EnrollRoute
  OperatorsRoute: typeof OperatorsRoute
  ReadyRoute: typeof ReadyRoute
  SignInRoute: typeof SignInRoute
  VerifyTotpRoute: typeof VerifyTotpRoute
  _localOperatorInvitationEmailRoute: typeof _localOperatorInvitationEmailRoute
  AuditEventIdRoute: typeof AuditEventIdRoute
  EnrollSecurityRoute: typeof EnrollSecurityRoute
  MerchantsMerchantIdRoute: typeof MerchantsMerchantIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMembersSearchRoute: typeof ApiMembersSearchRoute
  ApiMerchantsSplatRoute: typeof ApiMerchantsSplatRoute
  ApiOperationsSplatRoute: typeof ApiOperationsSplatRoute
  OperatorsInvitationsNewRoute: typeof OperatorsInvitationsNewRoute
  MerchantsMerchantIdMembersMemberIdRoute: typeof MerchantsMerchantIdMembersMemberIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-totp': {
      id: '/verify-totp'
      path: '/verify-totp'
      fullPath: '/verify-totp'
      preLoaderRoute: typeof VerifyTotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ready': {
      id: '/ready'
      path: '/ready'
      fullPath: '/ready'
      preLoaderRoute: typeof ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll': {
      id: '/enroll'
      path: '/enroll'
      fullPath: '/enroll'
      preLoaderRoute: typeof EnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchantId': {
      id: '/merchants/$merchantId'
      path: '/merchants/$merchantId'
      fullPath: '/merchants/$merchantId'
      preLoaderRoute: typeof MerchantsMerchantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enroll_/security': {
      id: '/enroll_/security'
      path: '/enroll/security'
      fullPath: '/enroll/security'
      preLoaderRoute: typeof EnrollSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit_/$eventId': {
      id: '/audit_/$eventId'
      path: '/audit/$eventId'
      fullPath: '/audit/$eventId'
      preLoaderRoute: typeof AuditEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__local/operator-invitation-email': {
      id: '/__local/operator-invitation-email'
      path: '/__local/operator-invitation-email'
      fullPath: '/__local/operator-invitation-email'
      preLoaderRoute: typeof _localOperatorInvitationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators_/invitations/new': {
      id: '/operators_/invitations/new'
      path: '/operators/invitations/new'
      fullPath: '/operators/invitations/new'
      preLoaderRoute: typeof OperatorsInvitationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/operations/$': {
      id: '/api/operations/$'
      path: '/api/operations/$'
      fullPath: '/api/operations/$'
      preLoaderRoute: typeof ApiOperationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merchants/$': {
      id: '/api/merchants/$'
      path: '/api/merchants/$'
      fullPath: '/api/merchants/$'
      preLoaderRoute: typeof ApiMerchantsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/members/search': {
      id: '/api/members/search'
      path: '/api/members/search'
      fullPath: '/api/members/search'
      preLoaderRoute: typeof ApiMembersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchants/$merchantId_/members/$memberId': {
      id: '/merchants/$merchantId_/members/$memberId'
      path: '/merchants/$merchantId/members/$memberId'
      fullPath: '/merchants/$merchantId/members/$memberId'
      preLoaderRoute: typeof MerchantsMerchantIdMembersMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  EnrollRoute: EnrollRoute,
  OperatorsRoute: OperatorsRoute,
  ReadyRoute: ReadyRoute,
  SignInRoute: SignInRoute,
  VerifyTotpRoute: VerifyTotpRoute,
  _localOperatorInvitationEmailRoute: _localOperatorInvitationEmailRoute,
  AuditEventIdRoute: AuditEventIdRoute,
  EnrollSecurityRoute: EnrollSecurityRoute,
  MerchantsMerchantIdRoute: MerchantsMerchantIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMembersSearchRoute: ApiMembersSearchRoute,
  ApiMerchantsSplatRoute: ApiMerchantsSplatRoute,
  ApiOperationsSplatRoute: ApiOperationsSplatRoute,
  OperatorsInvitationsNewRoute: OperatorsInvitationsNewRoute,
  MerchantsMerchantIdMembersMemberIdRoute:
    MerchantsMerchantIdMembersMemberIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
