// This module is generated by `pnpm -C packages/i18n generate` before checks.
// Keeping this stable package entry point means application code never imports
// the generated directory directly.
// oxlint-disable-next-line oxc/no-barrel-file -- this is the package's intentional typed message entry point
export * from './generated/messages.js'
